apiVersion: v1
kind: Service
metadata:
  name: eureka-service-ms-service
  namespace: eureka-service-ms-namespace
spec:
  selector:
    app: eureka-deployment
  ports:
    - protocol: "TCP"
      port: 8761
      targetPort: 8761
  type: NodePort